### ISSUE TITLE
new WebView(context)失败

### ISSUE THREAD

**Issue by timelikeswind** [JonaNorman/WebViewUpgrade#11]
应用首次打开正常，再次打开时，运行WebViewReplacer.java:checkWebView第170行：new WebView(context);出现异常：
```
ignored Vulkan layer search path /data/user/0/com.test.myapplication/files/com.google.android.webview/96.0.4664.92.apk-libs/arm64-v8a:/data/user/0/com.test.myapplication/files/com.google.android.webview/96.0.4664.92.apk!/lib/arm64-v8a for namespace 0x72956b30f0
Failed to bind to WebView service
com.norman.webviewup.lib.WebViewReplaceException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at android.app.ResourcesManager.appendLibAssetForMainAssetPath(ResourcesManager.java:895)
	at android.webkit.WebViewDelegate.addWebViewAssetPath(WebViewDelegate.java:205)
	at lE0.j(chromium-SystemWebViewGoogle.aab-stable-466409203:1)
	at com.android.webview.chromium.WebViewChromium.<init>(chromium-SystemWebViewGoogle.aab-stable-466409203:12)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.createWebView(chromium-SystemWebViewGoogle.aab-stable-466409203:1)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2336)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2395)
	at android.view.View.<init>(View.java:4023)
	at android.view.View.<init>(View.java:4146)
	at android.view.ViewGroup.<init>(ViewGroup.java:579)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
	at android.webkit.WebView.<init>(WebView.java:627)
	at android.webkit.WebView.<init>(WebView.java:572)
	at android.webkit.WebView.<init>(WebView.java:555)
	at android.webkit.WebView.<init>(WebView.java:542)
	at android.webkit.WebView.<init>(WebView.java:532)
	at com.norman.webviewup.lib.WebViewReplace.checkWebView(WebViewReplace.java:170)
	at com.norman.webviewup.lib.WebViewReplace.replace(WebViewReplace.java:64)
	at com.norman.webviewup.lib.WebViewUpgrade$1.lambda$onPrepareSuccess$0(WebViewUpgrade.java:92)
	at com.norman.webviewup.lib.WebViewUpgrade$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at com.norman.webviewup.lib.util.HandlerUtils.runInMainThread(HandlerUtils.java:11)
	at com.norman.webviewup.lib.WebViewUpgrade$1.onPrepareSuccess(WebViewUpgrade.java:88)
	at com.norman.webviewup.lib.source.UpgradeSource.lambda$prepare$0$com-norman-webviewup-lib-source-UpgradeSource(UpgradeSource.java:51)
	at com.norman.webviewup.lib.source.UpgradeSource$$ExternalSyntheticLambda2.run(D8$$SyntheticClass)
	at com.norman.webviewup.lib.util.HandlerUtils.runInMainThread(HandlerUtils.java:11)
	at com.norman.webviewup.lib.source.UpgradeSource.prepare(UpgradeSource.java:50)
	at com.norman.webviewup.lib.source.UpgradeSource.prepare(UpgradeSource.java:44)
	at com.norman.webviewup.lib.WebViewUpgrade.upgrade(WebViewUpgrade.java:85)
	at com.test.myapplication.App.onCreate(App.kt:41)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5405)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by JonaNorman** [comment]
描述一下复现场景，越详细越好

**Comment by timelikeswind** [comment]
在APP创建时调用：
```kotlin
class App : Application() {
    override fun onCreate() {
        super.onCreate()
        val upgradeSource = UpgradeAssetSource(this, "com.google.android.webview_96.0.4664.92.apk",
            File(applicationContext.filesDir, "com.google.android.webview/96.0.4664.92.apk"))
        WebViewUpgrade.addUpgradeCallback(object:UpgradeCallback{
            override fun onUpgradeProcess(percent: Float) {
                Log.i("WebViewUpgrade", percent.toString())
            }

            override fun onUpgradeComplete() {
                Log.i("WebViewUpgrade", "onUpgradeComplete")
            }

            override fun onUpgradeError(throwable: Throwable?) {
                throwable?.let{
                    Log.i("WebViewUpgradeError", it.stackTraceToString())
                }
            }
        })
        WebViewUpgrade.upgrade(upgradeSource)
    }
}
```

**Comment by timelikeswind** [comment]
应用首次打开时正常，再次打开时出现上述异常，需要每次清除数据后才能运行

**Comment by JonaNorman** [comment]
```
com.norman.webviewup.lib.WebViewReplaceException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at android.app.ResourcesManager.appendLibAssetForMainAssetPath(ResourcesManager.java:895)
```
	和
```
java.lang.ExceptionInInitializerError
	at org.chromium.base.BuildInfo.getAll(chromium-SystemWebViewGoogle.aab-stable-466409203:1)
```
上述两个日志，都是第二次打开时出现，两个复现场景有什么不一样，还有机型是什么

**Comment by timelikeswind** [comment]
只是首次打开退出后再次打开就会出现上述异常。机型一加5T，Android7.1

**Comment by timelikeswind** [comment]
需要另开一线程， `WebViewUpgrade.upgrade(upgradeSource)`
