### ISSUE TITLE
更新新版127.0.6533.103的Web内核报错

### ISSUE THREAD

**Issue by kbxwn** [JonaNorman/WebViewUpgrade#18]
你好，更新新版的Web内核会报错，目前在三星、华为手机上都会此错误，报错信息如下：
Chromium WebView package does not exist
                                                         android.webkit.WebViewFactory$MissingWebViewPackageException: Tried to load an invalid WebView provider: com.google.android.trichromelibrary
                                                         	at android.webkit.WebViewFactory.verifyPackageInfo(WebViewFactory.java:439)
                                                         	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:496)
                                                         	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:528)
                                                         	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:369)
                                                         	at android.webkit.WebView.getFactory(WebView.java:2609)
                                                         	at android.webkit.WebView.ensureProviderCreated(WebView.java:2603)
                                                         	at android.webkit.WebView.setOverScrollMode(WebView.java:2671)
                                                         	at android.view.View.<init>(View.java:5749)
                                                         	at android.view.View.<init>(View.java:5924)
                                                         	at android.view.ViewGroup.<init>(ViewGroup.java:712)
                                                         	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:59)
                                                         	at android.webkit.WebView.<init>(WebView.java:425)
                                                         	at android.webkit.WebView.<init>(WebView.java:367)
                                                         	at android.webkit.WebView.<init>(WebView.java:349)
                                                         	at android.webkit.WebView.<init>(WebView.java:336)
                                                         	at android.webkit.WebView.<init>(WebView.java:326)
                                                         	at com.norman.webviewup.lib.WebViewReplace.checkWebView(WebViewReplace.java:176)
                                                         	at com.norman.webviewup.lib.WebViewReplace.replace(WebViewReplace.java:64)
                                                         	at com.norman.webviewup.lib.WebViewUpgrade$1.lambda$onPrepareSuccess$0(WebViewUpgrade.java:96)
                                                         	at com.norman.webviewup.lib.WebViewUpgrade$1.$r8$lambda$r_H9cPIdaE6Exp6IS7D2zYtboBg(WebViewUpgrade.java:0)
                                                         	at com.norman.webviewup.lib.WebViewUpgrade$1$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
                                                         	at com.norman.webviewup.lib.util.HandlerUtils.runInMainThread(HandlerUtils.java:11)
                                                         	at com.norman.webviewup.lib.WebViewUpgrade$1.onPrepareSuccess(WebViewUpgrade.java:92)
                                                         	at com.norman.webviewup.lib.source.UpgradeSource.lambda$prepare$0(UpgradeSource.java:51)
                                                         	at com.norman.webviewup.lib.source.UpgradeSource.$r8$lambda$flPPiEgezh-0dy6RyYvFvCj8rRk(UpgradeSource.java:0)
                                                         	at com.norman.webviewup.lib.source.UpgradeSource$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:0)
                                                         	at android.os.Handler.handleCallback(Handler.java:958)
                                                         	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                         	at android.os.Looper.loopOnce(Looper.java:230)
                                                         	at android.os.Looper.loop(Looper.java:319)
                                                         	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                         	at java.lang.reflect.Method.invoke(Native Method)
                                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

Web内核下载地址(需要梯子）：https://www.apkmirror.com/apk/google-inc/trichrome-library/trichrome-library-127-0-6533-103-release/trichrome-library-127-0-6533-103-3-android-apk-download/download/?key=93dbfb3725354bbb0cd430a58664ce83f469cb45

能帮忙看下是什么原因吗，不胜感激

**Comment by RelaxPic** [comment]
我帮你看了一下。 
  private static void verifyPackageInfo(PackageInfo chosen, PackageInfo toUse)
      throws MissingWebViewPackageException {
    if (!chosen.packageName.equals(toUse.packageName)) {
      throw new MissingWebViewPackageException(
          "Failed to verify WebView provider, "
              + "packageName mismatch, expected: "
              + chosen.packageName
              + " actual: "
              + toUse.packageName);
    }
    if (chosen.getLongVersionCode() > toUse.getLongVersionCode()) {
      throw new MissingWebViewPackageException(
          "Failed to verify WebView provider, "
              + "version code is lower than expected: "
              + chosen.getLongVersionCode()
              + " actual: "
              + toUse.getLongVersionCode());
    }
    if (getWebViewLibrary(toUse.applicationInfo) == null) {
      throw new MissingWebViewPackageException(
          "Tried to load an invalid WebView provider: " + toUse.packageName);
    }
    if (!signaturesEquals(chosen.signatures, toUse.signatures)) {
      throw new MissingWebViewPackageException(
          "Failed to verify WebView provider, " + "signature mismatch");
    }
  }

其实就是签名不一致导致的坑。

**Comment by VoryWork** [comment]
试一下用这个行不行https://www.apkmirror.com/apk/google-inc/android-system-webview/android-system-webview-131-0-6778-105-release/

**Comment by kbxwn** [comment]
更换了其他的Web内核版本可以更新，但在某些手机上还是有报错，这应该还是无法避免的，非常感谢回复
