### ISSUE TITLE
请教下，内核x86_64用哪个版本？用x86的版本报错了？

### ISSUE THREAD

**Issue by xiaomomoni** [JonaNorman/WebViewUpgrade#22]
message:com.norman.webviewup.lib.reflect.ReflectException: java.lang.NullPointerException: unable to find supported abis [arm64-v8a, x86_64] in dir /data/user/0/cc.signworld.adpublish.ph.pictoscreen/files/com.google.android.webview/122.0.6261.64.apk-libs
stackTrace:com.norman.webviewup.lib.WebViewReplaceException: com.norman.webviewup.lib.reflect.ReflectException: java.lang.NullPointerException: unable to find supported abis [arm64-v8a, x86_64] in dir /data/user/0/cc.signworld.adpublish.ph.pictoscreen/files/com.google.android.webview/122.0.6261.64.apk-libs
	at java.lang.reflect.Method.invoke(Native Method)
	at com.norman.webviewup.lib.reflect.RuntimeProxy$1.onInvoke(RuntimeProxy.java:83)
	at com.norman.webviewup.lib.reflect.ReflectProxy$1.invoke(ReflectProxy.java:85)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy10.waitForAndGetProvider(Unknown Source)
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:369)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:439)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:251)
	at android.webkit.WebView.getFactory(WebView.java:2448)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2443)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2508)
	at android.view.View.<init>(View.java:4809)
	at android.view.View.<init>(View.java:4950)
	at android.view.ViewGroup.<init>(ViewGroup.java:659)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
	at android.webkit.WebView.<init>(WebView.java:405)
	at android.webkit.WebView.<init>(WebView.java:350)
	at android.webkit.WebView.<init>(WebView.java:333)
	at android.webkit.WebView.<init>(WebView.java:320)
	at android.webkit.WebView.<init>(WebView.java:310)
	at com.norman.webviewup.lib.WebViewReplace.checkWebView(WebViewReplace.java:170)
	at com.norman.webviewup.lib.WebViewReplace.replace(WebViewReplace.java:64)
	at com.norman.webviewup.lib.WebViewUpgrade$1.lambda$onPrepareSuccess$0(WebViewUpgrade.java:92)
	at com.norman.webviewup.lib.WebViewUpgrade$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at com.norman.webviewup.lib.util.HandlerUtils.runInMainThread(HandlerUtils.java:11)
	at com.norman.webviewup.lib.WebViewUpgrade$1.onPrepareSuccess(WebViewUpgrade.java:88)
	at com.norman.webviewup.lib.source.UpgradeSource.lambda$prepare$0$com-norman-webviewup-lib-source-UpgradeSource(UpgradeSource.java:51)
	at com.norman.webviewup.lib.source.UpgradeSource$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at com.norman.webviewup.lib.util.HandlerUtils.runInMainThread(HandlerUtils.java:11)
	at com.norman.webviewup.lib.source.UpgradeSource.prepare(UpgradeSource.java:50)
	at com.norman.webviewup.lib.source.UpgradeSource.prepare(UpgradeSource.java:44)
	at com.norman.webviewup.lib.WebViewUpgrade.upgrade(WebViewUpgrade.java:85)
	at cc.signworld.adpublish.ph.anoi.activity.WebkitActivity$3.onClick(WebkitActivity.java:219)
	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
	at android.widget.AbsListView$3.run(AbsListView.java:4052)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: com.norman.webviewup.lib.reflect.ReflectException: com.norman.webviewup.lib.reflect.ReflectException: java.lang.NullPointerException: unable to find supported abis [arm64-v8a, x86_64] in dir /data/user/0/cc.signworld.adpublish.ph.pictoscreen/files/com.google.android.webview/122.0.6261.64.apk-libs
	... 4

**Comment by JonaNorman** [comment]
从[apkmirror](https://www.apkmirror.com/apk/google-inc/android-system-webview/android-system-webview-122-0-6261-64-release/android-system-webview-122-0-6261-64-8-android-apk-download/)下载
