### ISSUE TITLE
117.0.0.0 升级118.0.5993.65报错

### ISSUE THREAD

**Issue by gmlymayday** [JonaNorman/WebViewUpgrade#23]
`message:WebView only can replace before System WebView init
                                                                                  stackTrace:com.norman.webviewup.lib.WebViewReplaceException: WebView only can replace before System WebView init
                                                                                  	at com.norman.webviewup.lib.WebViewReplace.checkWebView(WebViewReplace.java:168)
                                                                                  	at com.norman.webviewup.lib.WebViewReplace.replace(WebViewReplace.java:64)
                                                                                  	at com.norman.webviewup.lib.WebViewUpgrade$1.lambda$onPrepareSuccess$0(WebViewUpgrade.java:92)
                                                                                  	at com.norman.webviewup.lib.WebViewUpgrade$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                  	at com.norman.webviewup.lib.util.HandlerUtils.runInMainThread(HandlerUtils.java:11)
                                                                                  	at com.norman.webviewup.lib.WebViewUpgrade$1.onPrepareSuccess(WebViewUpgrade.java:88)
                                                                                  	at com.norman.webviewup.lib.source.UpgradeSource.lambda$prepare$0$com-norman-webviewup-lib-source-UpgradeSource(UpgradeSource.java:51)
                                                                                  	at com.norman.webviewup.lib.source.UpgradeSource$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
                                                                                  	at com.norman.webviewup.lib.util.HandlerUtils.runInMainThread(HandlerUtils.java:11)
                                                                                  	at com.norman.webviewup.lib.source.UpgradeSource.prepare(UpgradeSource.java:50)
                                                                                  	at com.norman.webviewup.lib.source.UpgradeSource.prepare(UpgradeSource.java:44)
                                                                                  	at com.norman.webviewup.lib.WebViewUpgrade.upgrade(WebViewUpgrade.java:85)
                                                                                  	at com.norman.webviewup.demo.MainActivity$3.onClick(MainActivity.java:210)
                                                                                  	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
                                                                                  	at android.widget.AdapterView.performItemClick(AdapterView.java:352)
                                                                                  	at android.widget.AbsListView.performItemClick(AbsListView.java:1277)
                                                                                  	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3294)
                                                                                  	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                  	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                  	at android.os.Looper.loopOnce(Looper.java:255)
                                                                                  	at android.os.Looper.loop(Looper.java:364)
                                                                                  	at android.app.ActivityThread.main(ActivityThread.java:8979)
                                                                                  	at java.lang.reflect.Method.invoke(Native Method)
                                                                                  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
                                                                                  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1053)`

**Comment by gmlymayday** [comment]
应该是下载的apk不对。现在成功了。
