### ISSUE TITLE
Android 14（API 级别 34）中，DexClassLoader 不再支持可写 dex/jar 文件

### ISSUE THREAD

**Issue by VoryWork** [JonaNorman/WebViewUpgrade#26]
Android 14（API 级别 34）中，DexClassLoader 不再支持从可写文件加载 dex/jar 文件。这意味着从Android 14开始，你不能再使用 DexClassLoader 来动态加载位于内部存储中的dex/jar文件，除非这些文件被设置为只读。

解决方法：

如果你需要动态加载代码，可以考虑将相关文件保存到外部存储中，并为这些文件设置正确的读权限。然后使用 DexClassLoader 从外部存储加载这些文件。

如果你需要保留文件在内部存储，并且只是想要一个可以工作的解决方案，可以考虑使用其他类加载器，如 PathClassLoader，来加载内部存储中的dex/jar文件。但请注意，这种方法可能会受到Android的安全和权限限制，因此可能需要你的应用具有特定的系统权限。

另一种方法是使用沙箱解决方案，如Google Play的App Sandbox，或者使用其他的动态代码加载技术，如Dynamical Loading Library（DL）。

**Comment by VoryWork** [comment]
message:java.lang.SecurityException: Writable dex file '/data/user/0/com.norman.webviewup.demo/files/com.google.android.webview/131.0.6778.135.apk' is not allowed.
                                                                                                    stackTrace:com.norman.webviewup.lib.WebViewReplaceException: java.lang.SecurityException: Writable dex file '/data/user/0/com.norman.webviewup.demo/files/com.google.android.webview/131.0.6778.135.apk' is not allowed.
                                                                                                    	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
                                                                                                    	at android.webkit.WebView.getFactory(WebView.java:2605)
                                                                                                    	at android.webkit.WebView.ensureProviderCreated(WebView.java:2599)
                                                                                                    	at android.webkit.WebView.setOverScrollMode(WebView.java:2667)
                                                                                                    	at android.view.View.<init>(View.java:5497)
                                                                                                    	at android.view.View.<init>(View.java:5638)
                                                                                                    	at android.view.ViewGroup.<init>(ViewGroup.java:704)
                                                                                                    	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
                                                                                                    	at android.webkit.WebView.<init>(WebView.java:421)
                                                                                                    	at android.webkit.WebView.<init>(WebView.java:363)
                                                                                                    	at android.webkit.WebView.<init>(WebView.java:345)
                                                                                                    	at android.webkit.WebView.<init>(WebView.java:332)
                                                                                                    	at android.webkit.WebView.<init>(WebView.java:322)
                                                                                                    	at com.norman.webviewup.lib.WebViewReplace.checkWebView(WebViewReplace.java:170)
                                                                                                    	at com.norman.webviewup.lib.WebViewReplace.replace(WebViewReplace.java:64)
                                                                                                    	at com.norman.webviewup.lib.WebViewUpgrade$1.lambda$onPrepareSuccess$0(WebViewUpgrade.java:92)
                                                                                                    	at com.norman.webviewup.lib.WebViewUpgrade$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at com.norman.webviewup.lib.util.HandlerUtils.runInMainThread(HandlerUtils.java:11)
                                                                                                    	at com.norman.webviewup.lib.WebViewUpgrade$1.onPrepareSuccess(WebViewUpgrade.java:88)
                                                                                                    	at com.norman.webviewup.lib.source.UpgradeSource.lambda$success$2$com-norman-webviewup-lib-source-UpgradeSource(UpgradeSource.java:81)
                                                                                                    	at com.norman.webviewup.lib.source.UpgradeSource$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: android.util.AndroidRuntimeException: java.lang.SecurityException: Writable dex file '/data/user/0/com.norman.webviewup.demo/files/com.google.android.webview/131.0.6778.135.apk' is not allowed.
                                                                                                    	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363) 
                                                                                                    	at android.webkit.WebView.getFactory(WebView.java:2605) 
                                                                                                    	at android.webkit.WebView.ensureProviderCreated(WebView.java:2599) 
                                                                                                    	at android.webkit.WebView.setOverScrollMode(WebView.java:2667) 
                                                                                                    	at android.view.View.<init>(View.java:5497) 
                                                                                                    	at android.view.View.<init>(View.java:5638) 
                                                                                                    	at android.view.ViewGroup.<init>(ViewGroup.java:704) 
                                                                                                    	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56) 
                                                                                                    	at android.webkit.WebView.<init>(WebView.java:421) 
                                                                                                    	at android.webkit.WebView.<init>(WebView.java:363) 
                                                                                                    	at android.webkit.WebView.<init>(WebView.java:345) 
                                                                                                    	at android.webkit.WebView.<init>(WebView.java:332) 
                                                                                                    	at android.webkit.WebView.<init>(WebView.java:322) 
                                                                                                    	at com.norman.webviewup.lib.WebViewReplace.checkWebView(WebViewReplace.java:170) 
                                                                                                    	at com.norman.webviewup.lib.WebViewReplace.replace(WebViewReplace.java:64) 
                                                                                                    	at com.norman.webviewup.lib.WebViewUpgrade$1.lambda$onPrepareSuccess$0(WebViewUpgrade.java:92) 
                                                                                                    	at com.norman.webviewup.lib.WebViewUpgrade$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
                                                                                                    	at com.norman.webviewup.lib.util.HandlerUtils.runInMainThread(HandlerUtils.java:11) 
                                                                                                    	at com.norman.webviewup.lib.WebViewUpgrade$1.onPrepareSuccess(WebViewUpgrade.java:88) 
                                                                                                    	at com.norman.webviewup.lib.source.UpgradeSource.lambda$success$2$com-norman-webviewup-lib-source-UpgradeSource(UpgradeSource.java:81) 
                                                                                                    	at com.norman.webviewup.lib.source.UpgradeSource$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
                                                                                                    Caused by: java.lang.SecurityException: Writable dex file '/data/user/0/com.norman.webviewup.demo/files/com.google.android.webview/131.0.6778.135.apk' is not allowed.
                                                                                                    	at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                                                    	at dalvik.system.DexFile.openDexFile(DexFile.java:406)
                                                                                                    	at dalvik.system.DexFile.<init>(DexFile.java:128)
                                                                                                    	at dalvik.system.DexFile.<init>(DexFile.java:101)
                                                                                                    	at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
                                                                                                    	at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
                                                                                                    	at dalvik.system.DexPathList.<init>(DexPathList.java:166)
                                                                                                    	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
                                                                                                    	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
                                                                                                    	at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
                                                                                                    	at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:93)
                                                                                                    	at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:134)
                                                                                                    	at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:126)
                                                                                                    	at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:61)
                                                                                                    	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1034)
                                                                                                    	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
                                                                                                    	at android.app.ContextImpl.getClassLoader(ContextImpl.java:499)
                                                                                                    	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:508)
