### ISSUE TITLE
【bug】如果系统不含WebView，无法Upgrade的问题（附解决思路）

### ISSUE THREAD

**Issue by 2980077544** [JonaNorman/WebViewUpgrade#6]
我针对WearOS手表进行开发，其不含WebView相关组件。

经测试，如果系统不含Android WebView，运行demo点Upgrade选择任一选项均会显示Fail。

看过logcat后，初步判断问题出在

http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/java/android/webkit/WebViewFactory.java

第375行处，抛出了一个异常。

***

如需方便的复现，可以在虚拟机的系统设置停用WebView应用程序。

**Comment by 2980077544** [comment]
按理来说这样应该可以解决问题：

`app/src/main/java/com/norman/webviewup/lib/service/interfaces`
```java
package com.norman.webviewup.lib.service.interfaces;

import android.content.pm.PackageInfo;

import com.norman.webviewup.lib.reflect.annotation.ClassName;
import com.norman.webviewup.lib.reflect.annotation.Field;


@ClassName(value = "android.webkit.WebViewProviderResponse")
public interface IWebViewProviderResponse {

    @Field(value = "packageInfo")
    void setPackageInfo(PackageInfo packageInfo);

    @Field(value = "packageInfo")
    PackageInfo getPackageInfo();


    @Field(value = "status")
    void setStatus(Object status);

}
```

`app/src/main/java/com/norman/webviewup/lib/hook`
```java
public class WebViewUpdateServiceHook extends BinderHook {

...

    private final WebViewUpdateServiceProxy proxy = new WebViewUpdateServiceProxy() {
        @Override
        protected Object waitForAndGetProvider() {
            Object result = invoke();
            PackageInfo packageInfo;
            try {
                packageInfo = context.getPackageManager()
                        .getPackageInfo(webViewPackageName,
                                PackageManager.GET_SHARED_LIBRARY_FILES
                                        | PackageManager.GET_SIGNATURES
                                        | PackageManager.GET_META_DATA);
            } catch (PackageManager.NameNotFoundException e) {
                throw new RuntimeException(e);
            }
            IWebViewProviderResponse webViewProviderResponse = RuntimeAccess.objectAccess(IWebViewProviderResponse.class, result);
            
            webViewProviderResponse.setPackageInfo(packageInfo);
            
            //http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/java/android/webkit/WebViewFactory.java#LIBLOAD_SUCCESS
            //public static final int LIBLOAD_SUCCESS = 0;
            webViewProviderResponse.setStatus(0);
            return result;
        }
```

但是会报这个错，望解答：
```
message:android.util.AndroidRuntimeException: com.norman.webviewup.lib.reflect.ReflectException: com.norman.webviewup.lib.reflect.ReflectException: java.lang.NoSuchFieldException: can not find filed: status
stackTrace:java.lang.RuntimeException: android.util.AndroidRuntimeException: com.norman.webviewup.lib.reflect.ReflectException: com.norman.webviewup.lib.reflect.ReflectException: java.lang.NoSuchFieldException: can not find filed: status
	at com.norman.webviewup.lib.WebViewUpgrade.replaceWebViewProvider(WebViewUpgrade.java:348)
	at com.norman.webviewup.lib.WebViewUpgrade.access$600(WebViewUpgrade.java:35)
	at com.norman.webviewup.lib.WebViewUpgrade$UPGRADE_ACTION.upgradeWebView(WebViewUpgrade.java:226)
	at com.norman.webviewup.lib.WebViewUpgrade$UPGRADE_ACTION.run(WebViewUpgrade.java:165)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.util.AndroidRuntimeException: com.norman.webviewup.lib.reflect.ReflectException: com.norman.webviewup.lib.reflect.ReflectException: java.lang.NoSuchFieldException: can not find filed: status
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
	at android.webkit.WebView.getFactory(WebView.java:2594)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2588)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2656)
	at android.view.View.<init>(View.java:5603)
	at android.view.View.<init>(View.java:5748)
	at android.view.ViewGroup.<init>(ViewGroup.java:709)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:421)
	at android.webkit.WebView.<init>(WebView.java:363)
	at android.webkit.WebView.<init>(WebView.java:345)
	at android.webkit.WebView.<init>(WebView.java:332)
	at android.webkit.WebView.<init>(WebView.java:322)
	at com.norman.webviewup.lib.WebViewUpgrade$1.run(WebViewUpgrade.java:315)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8103)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: com.norman.webviewup.lib.reflect.ReflectException: com.norman.webviewup.lib.reflect.ReflectException: java.lang.NoSuchFieldException: can not find filed: status
	at java.lang.reflect.Method.invoke(Native Method)
	at com.norman.webviewup.lib.reflect.RuntimeProxy$1.onInvoke(RuntimeProxy.java:83)
	at com.norman.webviewup.lib.reflect.ReflectProxy$1.invoke(ReflectProxy.java:85)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy13.waitForAndGetProvider(Unknown Source)
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:421)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:493)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:348)
	... 21 more
Caused by: com.norman.webviewup.lib.reflect.ReflectException: java.lang.NoSuchFieldException: can not find filed: status
	at com.norman.webviewup.lib.reflect.ReflectField.prepareFiled(ReflectField.java:126)
	at com.norman.webviewup.lib.reflect.ReflectField.set(ReflectField.java:68)
	at com.norman.webviewup.lib.reflect.RuntimeAccess$3.onInvoke(RuntimeAccess.java:149)
	at com.norman.webviewup.lib.reflect.ReflectProxy$1.invoke(ReflectProxy.java:85)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy16.setStatus(Unknown Source)
	at com.norman.webviewup.lib.hook.WebViewUpdateServiceHook$1.waitForAndGetProvider(WebViewUpdateServiceHook.java:52)
	... 29 more
Caused by: java.lang.NoSuchFieldException: can not find filed: status
	... 36 more

```

**Comment by JonaNorman** [comment]
改成试试
 @Field(value = "status")
    void setStatus(int status);

**Comment by 2980077544** [comment]
> 改成试试 @field(value = "status") void setStatus(int status);

问题类似，依旧不能使用 @JonaNorman

**Comment by Genouka** [comment]
@JonaNorman
